"""Generates Simplified Chinese names for Zed's actions.

Zed's command palette, keymap editor and which-key indicator show action names
that are computed at runtime from the action's Rust type name
(`command_palette::humanize_action_name`), so they never appear as string
literals in the source and cannot be picked up by a translation catalog. This
script extracts every action from the source tree, humanizes it the same way
Zed does, and composes a Simplified Chinese name for it.

    python script/localization/actions_zh_cn.py script/localization/actions_zh_cn.json

The result is a flat `humanized name -> translation` map that
`generate_zh_cn.py` merges into the interface dictionary.
"""

import json
import os
import re
import sys

# Phrases are matched longest first, so multi-word entries have to be listed
# before the single words they are built from.
PHRASES = [
    # Navigation and movement.
    ("go to", "转到"),
    ("goto", "转到"),
    ("move to", "移动到"),
    ("jump to", "跳转到"),
    ("switch to", "切换到"),
    ("change to", "更改为"),
    ("convert to", "转换为"),
    ("insert at", "插入到"),
    ("insert from", "从以下位置插入"),
    ("insert before", "在前面插入"),
    ("insert after", "在后面插入"),
    ("insert end of line", "在行尾插入"),
    ("insert first non whitespace", "在首个非空白字符处插入"),
    ("insert line above", "在上方插入行"),
    ("insert line below", "在下方插入行"),
    ("insert empty line above", "在上方插入空行"),
    ("insert empty line below", "在下方插入空行"),
    ("delete to end of line", "删除到行尾"),
    ("yank to end of line", "复制到行尾"),
    ("change to end of line", "更改到行尾"),
    ("start of line", "行首"),
    ("end of line", "行尾"),
    ("end of file", "文件末尾"),
    ("entire file", "整个文件"),
    ("first non whitespace", "首个非空白字符"),
    ("non whitespace", "非空白字符"),
    ("move down", "下移"),
    ("move up", "上移"),
    ("move left", "左移"),
    ("move right", "右移"),
    ("move to next", "移到下一个"),
    ("move to previous", "移到上一个"),
    ("line down", "向下移动一行"),
    ("line up", "向上移动一行"),
    ("page down", "向下翻页"),
    ("page up", "向上翻页"),
    ("half page down", "向下翻半页"),
    ("half page up", "向上翻半页"),
    ("half page left", "向左翻半页"),
    ("half page right", "向右翻半页"),
    ("scroll down", "向下滚动"),
    ("scroll up", "向上滚动"),
    ("scroll left", "向左滚动"),
    ("scroll right", "向右滚动"),
    ("select next", "选择下一个"),
    ("select previous", "选择上一个"),
    ("select all", "全选"),
    ("select line", "选择行"),
    ("select larger syntax node", "选择更大的语法节点"),
    ("select smaller syntax node", "选择更小的语法节点"),
    ("select next syntax node", "选择下一个语法节点"),
    ("select previous syntax node", "选择上一个语法节点"),
    ("select next match", "选择下一个匹配项"),
    ("select previous match", "选择上一个匹配项"),
    ("select next reference", "选择下一个引用"),
    ("select previous reference", "选择上一个引用"),
    ("move to next match", "移到下一个匹配项"),
    ("move to previous match", "移到上一个匹配项"),
    ("go to definition", "转到定义"),
    ("go to declaration", "转到声明"),
    ("go to implementation", "转到实现"),
    ("go to line", "转到行"),
    ("go to next reference", "转到下一个引用"),
    ("go to previous reference", "转到上一个引用"),
    ("go to next tab", "转到下一个标签页"),
    ("go to previous tab", "转到上一个标签页"),
    ("go to tab", "转到标签页"),
    ("go back", "后退"),
    ("go forward", "前进"),
    ("jump forward", "向前跳转"),
    ("jump backward", "向后跳转"),
    # Panes, docks and windows.
    ("split right", "向右拆分"),
    ("split left", "向左拆分"),
    ("split up", "向上拆分"),
    ("split down", "向下拆分"),
    ("split pane", "拆分窗格"),
    ("swap panes", "交换窗格"),
    ("reset pane sizes", "重置窗格大小"),
    ("resize pane", "调整窗格大小"),
    ("minimize pane", "最小化窗格"),
    ("maximize pane", "最大化窗格"),
    ("zoom pane", "缩放窗格"),
    ("toggle pane", "切换窗格"),
    ("close pane", "关闭窗格"),
    ("new pane", "新建窗格"),
    ("next pane", "下一个窗格"),
    ("previous pane", "上一个窗格"),
    ("left dock", "左侧停靠栏"),
    ("right dock", "右侧停靠栏"),
    ("bottom dock", "底部停靠栏"),
    ("toggle left dock", "切换左侧停靠栏"),
    ("toggle right dock", "切换右侧停靠栏"),
    ("toggle bottom dock", "切换底部停靠栏"),
    ("toggle sidebar", "切换侧边栏"),
    ("new window", "新建窗口"),
    ("close window", "关闭窗口"),
    ("new file", "新建文件"),
    ("new folder", "新建文件夹"),
    ("new terminal", "新建终端"),
    ("new thread", "新建会话"),
    ("new project", "新建项目"),
    ("new buffer", "新建缓冲区"),
    ("open recent", "打开最近项目"),
    ("open in", "在以下位置打开"),
    ("open file", "打开文件"),
    ("open folder", "打开文件夹"),
    ("reopen closed", "重新打开已关闭的"),
    ("close all", "全部关闭"),
    ("save all", "全部保存"),
    ("close other", "关闭其他"),
    # Panels.
    ("project panel", "项目面板"),
    ("outline panel", "大纲面板"),
    ("git panel", "Git 面板"),
    ("terminal panel", "终端面板"),
    ("debug panel", "调试面板"),
    ("agent panel", "智能体面板"),
    ("collab panel", "协作面板"),
    ("chat panel", "聊天面板"),
    ("notification panel", "通知面板"),
    ("toggle project panel", "切换项目面板"),
    ("toggle git panel", "切换 Git 面板"),
    ("toggle outline panel", "切换大纲面板"),
    ("toggle terminal panel", "切换终端面板"),
    ("toggle debug panel", "切换调试面板"),
    ("toggle agent panel", "切换智能体面板"),
    ("toggle collaboration panel", "切换协作面板"),
    ("toggle chat panel", "切换聊天面板"),
    # Editing.
    ("toggle comments", "切换注释"),
    ("toggle block comments", "切换块注释"),
    ("toggle line comments", "切换行注释"),
    ("comment", "注释"),
    ("comments", "注释"),
    ("upper case", "大写"),
    ("lower case", "小写"),
    ("uppercase", "大写"),
    ("lowercase", "小写"),
    ("change case", "更改大小写"),
    ("opposite case", "相反大小写"),
    ("convert to upper case", "转换为大写"),
    ("convert to lower case", "转换为小写"),
    ("auto indent", "自动缩进"),
    ("indent", "缩进"),
    ("outdent", "取消缩进"),
    ("join lines", "合并行"),
    ("join lines no whitespace", "合并行（不含空白）"),
    ("rewrap", "重新换行"),
    ("trim", "去除"),
    ("format", "格式化"),
    ("format document", "格式化文档"),
    ("newline", "换行"),
    ("backspace", "退格"),
    ("delete left", "向左删除"),
    ("delete right", "向右删除"),
    ("delete line", "删除行"),
    ("delete to end", "删除到末尾"),
    ("duplicate line", "复制行"),
    ("duplicate above", "在上方复制"),
    ("duplicate below", "在下方复制"),
    ("select line", "选择行"),
    ("expand selection", "扩展选区"),
    ("shrink selection", "缩小选区"),
    ("restore visual selection", "恢复可视选区"),
    ("undo", "撤销"),
    ("redo", "重做"),
    ("undo last", "撤销上一步"),
    ("repeat", "重复"),
    ("end repeat", "结束重复"),
    # Search, replace and find.
    ("find in files", "在文件中查找"),
    ("find all references", "查找所有引用"),
    ("find next", "查找下一个"),
    ("find previous", "查找上一个"),
    ("find", "查找"),
    ("finder", "查找器"),
    ("search", "搜索"),
    ("search submit", "提交搜索"),
    ("replace", "替换"),
    ("replace all", "全部替换"),
    ("toggle replace", "切换替换"),
    ("substitute", "替换"),
    ("substitute line", "替换行"),
    ("match case", "区分大小写"),
    ("matching", "匹配"),
    ("match", "匹配"),
    ("matches", "匹配项"),
    ("regex", "正则表达式"),
    ("whole word", "全字匹配"),
    ("filter", "筛选"),
    ("filters", "筛选器"),
    ("sort", "排序"),
    ("query", "查询"),
    # Files, buffers and projects.
    ("project", "项目"),
    ("workspace", "工作区"),
    ("worktree", "工作树"),
    ("buffer", "缓冲区"),
    ("multibuffer", "多缓冲区"),
    ("directory", "目录"),
    ("folder", "文件夹"),
    ("file", "文件"),
    ("files", "文件"),
    ("filesystem", "文件系统"),
    ("path", "路径"),
    ("relative path", "相对路径"),
    ("absolute path", "绝对路径"),
    ("copy path", "复制路径"),
    ("recent", "最近"),
    ("recent projects", "最近的项目"),
    ("snippet", "代码片段"),
    ("snippets", "代码片段"),
    ("symbol", "符号"),
    ("symbols", "符号"),
    ("syntax", "语法"),
    ("language", "语言"),
    ("languages", "语言"),
    # Git.
    ("git", "Git"),
    ("branch", "分支"),
    ("branches", "分支"),
    ("commit", "提交"),
    ("commits", "提交"),
    ("stash", "暂存"),
    ("staged", "已暂存"),
    ("unstaged", "未暂存"),
    ("stage", "暂存"),
    ("unstage", "取消暂存"),
    ("staging", "暂存区"),
    ("push", "开始"),
    ("pull", "拉取"),
    ("fetch", "获取"),
    ("remote", "远程"),
    ("remotes", "远程"),
    ("repository", "仓库"),
    ("repo", "仓库"),
    ("registry", "注册表"),
    ("diff", "差异"),
    ("blame", "追溯"),
    ("merge", "合并"),
    ("rebase", "变基"),
    ("conflict", "冲突"),
    ("conflicted", "冲突的"),
    ("conflicts", "冲突"),
    ("compare", "比较"),
    ("checkout", "检出"),
    ("discard", "丢弃"),
    ("restore", "恢复"),
    ("uncommit", "取消提交"),
    ("tag", "标签"),
    ("sha", "SHA"),
    ("head", "HEAD"),
    ("base", "基准"),
    ("upstream", "上游"),
    ("force", "强制"),
    ("forced", "强制"),
    # Debugger.
    ("debugger", "调试器"),
    ("debug", "调试"),
    ("breakpoint", "断点"),
    ("breakpoints", "断点"),
    ("continue", "继续"),
    ("step over", "单步跳过"),
    ("step into", "单步进入"),
    ("step out", "单步跳出"),
    ("step back", "单步后退"),
    ("pause", "暂停"),
    ("call stack", "调用堆栈"),
    ("variables", "变量"),
    ("variable", "变量"),
    ("console", "控制台"),
    ("output", "输出"),
    ("outputs", "输出"),
    ("evaluate", "求值"),
    ("expression", "表达式"),
    ("arguments", "参数"),
    ("argument", "参数"),
    ("launch", "启动"),
    ("attach", "附加"),
    ("adapter", "适配器"),
    ("session", "会话"),
    ("sessions", "会话"),
    ("specs", "配置"),
    ("dump", "转储"),
    ("heap", "堆"),
    ("profile", "性能分析"),
    ("profiles", "性能分析"),
    ("tracing", "跟踪"),
    ("trace", "跟踪"),
    ("latency", "延迟"),
    ("frame", "帧"),
    ("frames", "帧"),
    ("histogram", "直方图"),
    ("granularity", "粒度"),
    ("memory", "内存"),
    # Collaboration.
    ("collab", "协作"),
    ("collaboration", "协作"),
    ("share", "共享"),
    ("screen share", "共享屏幕"),
    ("follow", "跟随"),
    ("follower", "跟随者"),
    ("following", "跟随中"),
    ("leader", "主导者"),
    ("participant", "参与者"),
    ("participants", "参与者"),
    ("room", "房间"),
    ("leave", "离开"),
    ("call", "调用"),
    ("calls", "调用"),
    ("mute", "静音"),
    ("deafen", "静听"),
    ("video", "视频"),
    ("audio", "音频"),
    ("channel", "频道"),
    ("channels", "频道"),
    ("thread", "会话"),
    ("threads", "会话"),
    ("chat", "聊天"),
    ("message", "消息"),
    ("messages", "消息"),
    ("contact", "联系人"),
    ("contacts", "联系人"),
    ("account", "账户"),
    ("sign in", "登录"),
    ("sign out", "退出登录"),
    ("log in", "登录"),
    ("log out", "退出登录"),
    # Agent and AI.
    ("agent", "智能体"),
    ("agents", "智能体"),
    ("agentic", "智能体"),
    ("model", "模型"),
    ("models", "模型"),
    ("prompt", "提示词"),
    ("context", "上下文"),
    ("permission", "权限"),
    ("permissions", "权限"),
    ("thinking", "思考"),
    ("effort", "强度"),
    ("favorite", "收藏"),
    ("queue", "队列"),
    ("queued", "排队中的"),
    ("inline assist", "行内辅助"),
    ("assist", "辅助"),
    ("prediction", "预测"),
    ("predictions", "预测"),
    ("predict", "预测"),
    ("completion", "补全"),
    ("completions", "补全"),
    ("skill", "技能"),
    ("skills", "技能"),
    ("rule", "规则"),
    ("rules", "规则"),
    ("summary", "摘要"),
    ("steer", "引导"),
    ("excerpts", "摘录"),
    ("sources", "来源"),
    ("migration", "迁移"),
    ("toolchain", "工具链"),
    ("tool", "工具"),
    ("tools", "工具"),
    ("authorize", "授权"),
    ("allow", "允许"),
    ("deny", "拒绝"),
    ("reject", "拒绝"),
    ("once", "一次"),
    ("always", "始终"),
    ("permanent", "永久"),
    # Editor chrome.
    ("editor", "编辑器"),
    ("tab", "标签页"),
    ("tabs", "标签页"),
    ("pane", "窗格"),
    ("panes", "窗格"),
    ("dock", "停靠栏"),
    ("docks", "停靠栏"),
    ("layout", "布局"),
    ("menu", "菜单"),
    ("palette", "面板"),
    ("command palette", "命令面板"),
    ("keymap editor", "键映射编辑器"),
    ("keymap", "键映射"),
    ("keybinds", "按键绑定"),
    ("key binding", "按键绑定"),
    ("key bindings", "按键绑定"),
    ("keybinding", "按键绑定"),
    ("keybindings", "按键绑定"),
    ("binding", "绑定"),
    ("bindings", "绑定"),
    ("keystroke", "按键"),
    ("keystrokes", "按键"),
    ("unbind", "解绑"),
    ("key", "按键"),
    ("settings", "设置"),
    ("settings editor", "设置编辑器"),
    ("theme", "主题"),
    ("extension", "扩展"),
    ("extensions", "扩展"),
    ("install", "安装"),
    ("installed", "已安装"),
    ("uninstall", "卸载"),
    ("update", "更新"),
    ("updates", "更新"),
    ("release", "发布"),
    ("check", "检查"),
    ("notification", "通知"),
    ("notifications", "通知"),
    ("welcome", "欢迎"),
    ("onboarding", "引导"),
    ("modal", "模态框"),
    ("pop", "弹出"),
    ("dropdown", "下拉菜单"),
    ("picker", "选择器"),
    ("selector", "选择器"),
    ("switcher", "切换器"),
    ("input", "输入"),
    ("text", "文本"),
    ("text input", "文本输入框"),
    ("user", "用户"),
    ("value", "值"),
    ("set", "设置"),
    ("unset", "取消设置"),
    ("use", "使用"),
    ("type", "类型"),
    ("row", "行"),
    ("column", "列"),
    ("cell", "单元格"),
    ("object", "对象"),
    ("string", "字符串"),
    ("data", "数据"),
    ("database", "数据库"),
    ("server", "服务器"),
    ("client", "客户端"),
    ("request", "请求"),
    ("response", "响应"),
    ("url", "URL"),
    ("link", "链接"),
    ("email", "邮箱"),
    ("address", "地址"),
    ("location", "位置"),
    ("status", "状态"),
    ("level", "级别"),
    ("range", "范围"),
    ("count", "数量"),
    ("size", "大小"),
    ("sizes", "大小"),
    ("zoom", "缩放"),
    ("font", "字体"),
    ("space", "空格"),
    ("whitespace", "空白"),
    ("white", "空白"),
    ("indentation", "缩进"),
    ("direction", "方向"),
    ("vertical", "垂直"),
    ("horizontal", "水平"),
    ("above", "上方"),
    ("below", "下方"),
    ("before", "之前"),
    ("after", "之后"),
    ("nearest", "最近的"),
    ("adjacent", "相邻的"),
    ("parent", "父级"),
    ("child", "子级"),
    ("children", "子级"),
    ("sibling", "同级"),
    ("group", "分组"),
    ("groups", "分组"),
    ("list", "列表"),
    ("tree", "树"),
    ("node", "节点"),
    ("entry", "条目"),
    ("entries", "条目"),
    ("item", "条目"),
    ("items", "条目"),
    ("part", "部分"),
    ("whole", "整个"),
    ("entire", "整个"),
    ("other", "其他"),
    ("others", "其他"),
    ("some", "一些"),
    ("any", "任意"),
    ("all", "全部"),
    ("none", "无"),
    ("current", "当前"),
    ("active", "活动"),
    ("inactive", "非活动"),
    ("selected", "选中的"),
    ("hidden", "隐藏的"),
    ("marked", "已标记"),
    ("ignored", "已忽略"),
    ("available", "可用"),
    ("required", "必需"),
    ("default", "默认"),
    ("custom", "自定义"),
    ("local", "本地"),
    ("locally", "本地"),
    ("native", "原生"),
    ("external", "外部"),
    ("temporary", "临时"),
    ("classic", "经典"),
    ("alternate", "备用"),
    ("secondary", "次要"),
    ("primary", "主要"),
    ("alpha", "Alpha"),
    ("beta", "Beta"),
    ("full", "完整"),
    ("larger", "更大"),
    ("smaller", "更小"),
    ("longer", "更长"),
    ("shorter", "更短"),
    ("longest", "最长"),
    ("newer", "更新的"),
    ("older", "更旧的"),
    ("newest", "最新的"),
    ("first", "第一个"),
    ("last", "最后一个"),
    ("next", "下一个"),
    ("previous", "上一个"),
    ("prev", "上一个"),
    ("top", "顶部"),
    ("bottom", "底部"),
    ("center", "居中"),
    ("middle", "中间"),
    ("left", "左"),
    ("right", "右"),
    ("up", "上"),
    ("down", "下"),
    ("forward", "前进"),
    ("back", "后退"),
    ("in", "于"),
    ("into", "到"),
    ("out", "外"),
    ("over", "上方"),
    ("from", "从"),
    ("with", "使用"),
    ("without", "不使用"),
    ("for", "用于"),
    ("by", "按"),
    ("and", "和"),
    ("of", "的"),
    ("the", ""),
    ("to", ""),
    ("as", "为"),
    ("at", "于"),
    ("no", "无"),
    ("not", "不"),
    ("more", "更多"),
    ("less", "更少"),
    ("increase", "增大"),
    ("decrease", "减小"),
    ("increment", "递增"),
    ("decrement", "递减"),
    ("advance", "前进"),
    ("alternate", "交替"),
    ("cycle", "循环"),
    ("toggle", "切换"),
    ("open", "打开"),
    ("close", "关闭"),
    ("closed", "已关闭"),
    ("save", "保存"),
    ("delete", "删除"),
    ("remove", "移除"),
    ("rename", "重命名"),
    ("duplicate", "创建副本"),
    ("copy", "复制"),
    ("cut", "剪切"),
    ("paste", "粘贴"),
    ("select", "选择"),
    ("selection", "选区"),
    ("selections", "选区"),
    ("focus", "聚焦"),
    ("activate", "激活"),
    ("show", "显示"),
    ("hide", "隐藏"),
    ("reveal", "显示"),
    ("expand", "展开"),
    ("collapse", "折叠"),
    ("fold", "折叠"),
    ("unfold", "展开"),
    ("insert", "插入"),
    ("append", "追加"),
    ("edit", "编辑"),
    ("view", "视图"),
    ("run", "运行"),
    ("rerun", "重新运行"),
    ("stop", "停止"),
    ("start", "开始"),
    ("finish", "完成"),
    ("restart", "重启"),
    ("rebuild", "重新构建"),
    ("reload", "重新加载"),
    ("refresh", "刷新"),
    ("reset", "重置"),
    ("clear", "清除"),
    ("add", "添加"),
    ("create", "创建"),
    ("new", "新建"),
    ("apply", "应用"),
    ("configure", "配置"),
    ("manage", "管理"),
    ("manager", "管理器"),
    ("handle", "处理"),
    ("resolve", "解决"),
    ("compose", "撰写"),
    ("send", "发送"),
    ("submit", "提交"),
    ("confirm", "确认"),
    ("cancel", "取消"),
    ("accept", "接受"),
    ("dismiss", "关闭"),
    ("ignore", "忽略"),
    ("keep", "保留"),
    ("pin", "固定"),
    ("unpin", "取消固定"),
    ("download", "下载"),
    ("upload", "上传"),
    ("archive", "归档"),
    ("review", "审查"),
    ("notes", "笔记"),
    ("log", "日志"),
    ("logs", "日志"),
    ("journal", "日志"),
    ("docs", "文档"),
    ("report", "报告"),
    ("bug", "缺陷"),
    ("crash", "崩溃"),
    ("panic", "恐慌"),
    ("hang", "挂起"),
    ("hangy", "卡顿"),
    ("error", "错误"),
    ("errors", "错误"),
    ("warning", "警告"),
    ("warnings", "警告"),
    ("info", "信息"),
    ("hint", "提示"),
    ("hints", "提示"),
    ("highlights", "高亮"),
    ("highlights", "高亮"),
    ("inspector", "检查器"),
    ("overlay", "覆盖层"),
    ("metadata", "元数据"),
    ("semantic", "语义"),
    ("token", "标记"),
    ("tokens", "标记"),
    ("subword", "子词"),
    ("motion", "移动"),
    ("register", "注册"),
    ("registers", "寄存器"),
    ("record", "录制"),
    ("recording", "录制"),
    ("replay", "重放"),
    ("exchange", "交换"),
    ("surround", "环绕"),
    ("surrounds", "环绕"),
    ("quotes", "引号"),
    ("brackets", "括号"),
    ("bars", "竖线"),
    ("pair", "对"),
    ("mini", "迷你"),
    ("inner", "内部"),
    ("outer", "外部"),
    ("shell", "Shell"),
    ("exec", "执行"),
    ("cli", "命令行"),
    ("console", "控制台"),
    ("container", "容器"),
    ("integration", "集成"),
    ("feature", "功能"),
    ("job", "任务"),
    ("task", "任务"),
    ("tasks", "任务"),
    ("simulate", "模拟"),
    ("exact", "精确"),
    ("actual", "实际"),
    ("immediately", "立即"),
    ("trial", "试用"),
    ("upsell", "升级提示"),
    ("exhausted", "已用尽"),
    ("quick", "快速"),
    ("fast", "快速"),
    ("slow", "慢速"),
    ("watching", "监视"),
    ("watch", "监视"),
    ("accessibility", "无障碍"),
    ("a11y", "无障碍"),
    ("example", "示例"),
    ("only", "仅"),
    ("test", "测试"),
    ("tests", "测试"),
    ("integration test", "集成测试"),
    ("benchmark", "基准测试"),
    ("spec", "规范"),
    ("implementation", "实现"),
    ("declaration", "声明"),
    ("definition", "定义"),
    ("reference", "引用"),
    ("references", "引用"),
    ("diagnostic", "诊断"),
    ("diagnostics", "诊断"),
    ("code action", "代码操作"),
    ("actions", "操作"),
    ("action", "操作"),
    ("command", "命令"),
    ("commands", "命令"),
    ("operator", "操作符"),
    ("operators", "操作符"),
    ("comment", "注释"),
    ("fold", "折叠"),
    ("thumbs", "点赞"),
    ("no thumbs", "取消点赞"),
    ("fps", "帧率"),
    ("gamma", "伽马"),
    ("scheme", "配色方案"),
    ("histogram", "直方图"),
    ("foreground", "前台"),
    ("background", "后台"),
    ("slot", "槽位"),
    ("pattern", "模式"),
    ("type", "类型"),
    ("double", "双"),
    ("forced", "强制"),
    ("fit", "适应"),
    ("fill", "填充"),
    ("place", "放置"),
    ("load", "加载"),
    ("loaded", "已加载"),
    ("launch", "启动"),
    ("disconnect", "断开连接"),
    ("reconnect", "重新连接"),
    ("shutdown", "关闭"),
    ("spawn", "启动"),
    ("detach", "分离"),
    ("delta", "增量"),
    ("rate", "速率"),
    ("timeout", "超时"),
    ("stats", "统计"),
    ("wsl", "WSL"),
    ("zed", "Zed"),
    ("etw", "ETW"),
    ("acp", "ACP"),
    ("mcp", "MCP"),
    ("lsp", "LSP"),
    ("json", "JSON"),
    ("vim", "Vim"),
    ("helix", "Helix"),
    ("vi", "Vi"),
    ("vs", "对比"),
    ("rot13", "ROT13"),
    ("rot47", "ROT47"),
    ("kernelspecs", "内核规范"),
    ("kernel", "内核"),
    ("notebook", "笔记本"),
    ("markdown", "Markdown"),
    ("clipboard", "剪贴板"),
    ("history", "历史记录"),
    ("browser", "浏览器"),
    ("preview", "预览"),
    ("sidebar", "侧边栏"),
    ("panel", "面板"),
    ("ui", "界面"),
    ("interface", "界面"),
    ("elements", "元素"),
    ("frame", "帧"),
    ("frames", "帧"),
    ("application", "应用程序"),
    ("windows", "窗口"),
    ("immediately", "立即"),
    ("marked", "已标记"),
    ("sensitive", "敏感"),
    ("excerpts", "摘录"),
    ("keystroke", "按键"),
    ("direction", "方向"),
    ("follow", "跟随"),
    ("chat", "聊天"),
    ("quotes", "引号"),
    ("reply", "回复"),
    ("replies", "回复"),
    ("edit", "编辑"),
    ("terminal", "终端"),
    ("outline", "大纲"),
    ("search", "搜索"),
    ("debugger", "调试器"),
    ("workspace", "工作区"),
    ("project", "项目"),
    ("dev", "开发"),
    ("admin", "管理员"),
    ("deploy", "打开"),
    ("keymap", "键映射"),
    ("authors", "作者"),
    ("integration", "集成"),
    # Shapes that read better as a whole than word by word.
    ("beginning of line", "行首"),
    ("delete to beginning of line", "删除到行首"),
    ("move to beginning of line", "移到行首"),
    ("delete to end of line", "删除到行尾"),
    ("view release notes locally", "在本地查看发布说明"),
    ("view release notes", "查看发布说明"),
    ("release notes", "发布说明"),
    ("scroll output", "滚动输出"),
    ("scroll output to bottom", "将输出滚动到底部"),
    ("scroll output to top", "将输出滚动到顶部"),
    ("run to cursor", "运行到光标处"),
    ("copy commit sha", "复制提交 SHA"),
    ("fit to view", "适应视图"),
    ("open without dismiss", "打开但不关闭"),
    ("split selection into lines", "将选区拆分为多行"),
    ("move down by lines", "按行下移"),
    ("move up by lines", "按行上移"),
    ("toggle block quote", "切换块引用"),
    ("enter command mode", "进入命令模式"),
    ("add watch", "添加监视"),
    ("clear current output", "清除当前输出"),
    ("toggle semantic tokens", "切换语义标记"),
    ("collapse nav entry", "折叠导航条目"),
    ("activate changes tab", "激活更改标签页"),
    ("activate attach tab", "激活附加标签页"),
    ("merge all windows", "合并所有窗口"),
    ("focus predictions", "聚焦预测"),
    ("open git integration onboarding", "打开 Git 集成引导"),
    ("clear history", "清除历史记录"),
    ("secondary test action", "次要测试操作"),
    ("close workspace sidebar", "关闭工作区侧边栏"),
    ("workspace sidebar", "工作区侧边栏"),
    ("move channel down", "将频道下移"),
    ("move channel up", "将频道上移"),
    ("cycle branch filter", "循环切换分支筛选"),
    ("cycle mode selector", "循环切换模式选择器"),
    ("show all branches", "显示所有分支"),
    ("show local branches", "显示本地分支"),
    ("show remote branches", "显示远程分支"),
    ("deploy replace", "打开替换"),
    ("deploy", "打开"),
    # Words.
    ("mode", "模式"),
    ("import", "导入"),
    ("end", "末尾"),
    ("options", "选项"),
    ("move", "移动"),
    ("line", "行"),
    ("lines", "行"),
    ("scroll", "滚动"),
    ("go", "转到"),
    ("visual", "可视"),
    ("page", "页"),
    ("switch", "切换"),
    ("split", "拆分"),
    ("nav", "导航"),
    ("yank", "复制"),
    ("quit", "退出"),
    ("cursor", "光标"),
    ("block", "块"),
    ("swap", "交换"),
    ("change", "更改"),
    ("changes", "更改"),
    ("case", "大小写"),
    ("step", "单步"),
    ("code", "代码"),
    ("word", "单词"),
    ("enter", "进入"),
    ("join", "合并"),
    ("half", "半"),
    ("convert", "转换"),
    ("normal", "普通"),
    ("resize", "调整大小"),
    ("inline", "行内"),
    ("beginning", "开头"),
    ("side", "侧"),
    ("field", "字段"),
    ("member", "成员"),
    ("screen", "屏幕"),
    ("property", "属性"),
    ("name", "名称"),
    ("drop", "拖放"),
    ("result", "结果"),
    ("results", "结果"),
    ("interrupt", "中断"),
    ("multi", "多"),
    ("root", "根目录"),
    ("minimize", "最小化"),
    ("character", "字符"),
    ("home", "行首"),
    ("auto", "自动"),
    ("empty", "空"),
    ("incoming", "传入"),
    ("outgoing", "传出"),
    ("control", "控制"),
    ("binary", "二进制"),
    ("modules", "模块"),
    ("enable", "启用"),
    ("changed", "已更改"),
    ("quote", "引用"),
    ("clean", "清理"),
    ("reopen", "重新打开"),
    ("include", "包含"),
    ("graph", "图表"),
    ("viewer", "查看器"),
    ("process", "进程"),
    ("zeta", "Zeta"),
    ("sidebar", "侧边栏"),
    ("feedback", "反馈"),
    ("projects", "项目"),
    ("keystroke input", "按键输入"),
    ("modal", "对话框"),
    ("onboarding", "引导"),
    ("image", "图片"),
    ("repl", "REPL"),
    ("svg", "SVG"),
    ("bedrock", "Bedrock"),
    ("counter", "计数器"),
    ("tabular data", "表格数据"),
    ("livekit client", "LiveKit 客户端"),
    # Second pass: shapes whose word-by-word composition put the words in the
    # wrong order, or picked the wrong sense of an ambiguous word.
    ("zoom in", "放大"),
    ("zoom out", "缩小"),
    ("zoom to actual size", "缩放至实际大小"),
    ("view staged changes", "查看已暂存更改"),
    ("view unstaged changes", "查看未暂存更改"),
    ("delete to", "删除到"),
    ("select to", "选择到"),
    ("cut to end of line", "剪切到行尾"),
    ("fold at level", "按层级折叠"),
    ("to clipboard", "到剪贴板"),
    ("from clipboard", "从剪贴板"),
    ("in new window", "在新窗口中"),
    ("at head", "在 HEAD 处"),
    ("from project", "从项目"),
    ("from remote", "从远程"),
    ("from other channels", "从其他频道"),
    ("in directory", "在目录中"),
    ("in new", "在新位置"),
    ("multi select next", "多选下一个"),
    ("toggle multi select", "切换多选"),
    ("multi select", "多选"),
    ("thumbs up", "点赞"),
    ("thumbs down", "点踩"),
    ("compare with branch", "与分支比较"),
    ("set group by", "设置分组方式为"),
    ("set sort by", "设置排序方式为"),
    ("select down by lines", "按行向下选择"),
    ("select up by lines", "按行向上选择"),
    ("tab stop", "制表位"),
    ("scroll to bottom", "滚动到底部"),
    ("scroll to top", "滚动到顶部"),
    ("scroll cursor bottom", "将光标滚动到底部"),
    ("scroll cursor center", "将光标滚动到中间"),
    ("scroll cursor top", "将光标滚动到顶部"),
    ("open preview to the side", "在侧边打开预览"),
    ("open markdown preview", "打开 Markdown 预览"),
    ("open following preview", "打开跟随预览"),
    ("open split horizontal", "在水平拆分中打开"),
    ("open split vertical", "在垂直拆分中打开"),
    ("split and move down", "拆分并下移"),
    ("split and move up", "拆分并上移"),
    ("split and move left", "拆分并左移"),
    ("split and move right", "拆分并右移"),
    ("items to the left", "左侧条目"),
    ("items to the right", "右侧条目"),
    ("swap item left", "向左交换条目"),
    ("swap item right", "向右交换条目"),
    ("hide hidden", "隐藏隐藏项"),
    ("hide git ignore", "隐藏 gitignore 项"),
    ("open permanent", "固定打开"),
    ("toggle active editor pin", "固定或取消固定活动编辑器"),
    ("toggle pin tab", "固定或取消固定标签页"),
    ("email zed", "发送邮件给 Zed"),
    ("file bug report", "提交缺陷报告"),
    ("request feature", "请求新功能"),
    ("register zed scheme", "注册 Zed 协议"),
    ("cli binary", "命令行程序"),
    ("send immediately", "立即发送"),
    ("allow always", "始终允许"),
    ("chat with follow", "与跟随者聊天"),
    ("load thread from clipboard", "从剪贴板加载会话"),
    ("copy thread to clipboard", "复制会话到剪贴板"),
    ("import threads from other channels", "从其他频道导入会话"),
    ("new native agent thread from summary", "从摘要新建原生智能体会话"),
    ("new external agent thread", "新建外部智能体会话"),
    ("resolve conflicted files with agent", "使用智能体解决冲突文件"),
    ("resolve conflicts with agent", "使用智能体解决冲突"),
    ("select next thread match", "选择下一个匹配的会话"),
    ("select previous thread match", "选择上一个匹配的会话"),
    ("drop stash item", "丢弃暂存条目"),
    ("open worktree in new window", "在新窗口打开工作树"),
    ("open file at head", "打开 HEAD 处的文件"),
    ("move project to new window", "将项目移到新窗口"),
    ("move project down", "将项目下移"),
    ("move project up", "将项目上移"),
    ("rerun rules to skills migration", "重新运行规则到技能的迁移"),
    ("continue thread", "继续线程"),
    ("thread picker", "线程选择器"),
    ("focus frames", "聚焦调用栈帧"),
    ("focus loaded sources", "聚焦已加载的源"),
    ("show incoming calls", "显示传入调用"),
    ("show outgoing calls", "显示传出调用"),
    ("add selection above", "在上方添加选区"),
    ("add selection below", "在下方添加选区"),
    ("unset breakpoint", "取消断点"),
    ("toggle data breakpoint", "切换数据断点"),
    ("toggle enable breakpoint", "切换启用断点"),
    ("toggle ignore breakpoints", "切换忽略断点"),
    ("open url prompt", "打开 URL 输入框"),
    ("reset frame overlay stats", "重置帧覆盖层统计"),
    ("join all", "合并全部"),
    ("join into next", "合并到下一个"),
    ("open in active pane", "在活动窗格中打开"),
    ("toggle registers view", "切换寄存器视图"),
    ("push register", "压入寄存器"),
    ("record register", "录制寄存器"),
    ("replay register", "重放寄存器"),
    ("set menus", "设置菜单"),
    ("open dev container", "打开开发容器"),
    ("open folder in wsl", "在 WSL 中打开文件夹"),
    ("open wsl", "打开 WSL"),
    ("add to workspace", "添加到工作区"),
    ("simulate disconnect", "模拟断开连接"),
    ("simulate timeout", "模拟超时"),
    ("show character palette", "显示字符面板"),
    ("send keystroke", "发送按键"),
    ("send text", "发送文本"),
    ("paste text", "粘贴文本"),
    ("rename terminal", "重命名终端"),
    ("rerun task", "重新运行任务"),
    ("toggle vi mode", "切换 Vi 模式"),
    ("create remote", "创建远程"),
    ("create worktree", "创建工作树"),
    ("select repo", "选择仓库"),
    ("project diff", "项目差异"),
    ("review diff", "审查差异"),
    ("rename branch", "重命名分支"),
    ("restore file", "恢复文件"),
    ("stage and next", "暂存并跳到下一个"),
    ("unstage and next", "取消暂存并跳到下一个"),
    ("stage range", "暂存范围"),
    ("filter remotes", "筛选远程"),
    ("leader and follower", "主导者和跟随者"),
    ("switch worktree", "切换工作树"),
    ("toggle diff base", "切换差异基准"),
    ("toggle staged", "切换已暂存"),
    ("focus first nav entry", "聚焦第一个导航条目"),
    ("focus last nav entry", "聚焦最后一个导航条目"),
    ("focus next nav entry", "聚焦下一个导航条目"),
    ("focus previous nav entry", "聚焦上一个导航条目"),
    ("focus next root nav entry", "聚焦下一个根级导航条目"),
    ("focus previous root nav entry", "聚焦上一个根级导航条目"),
    ("focus next file", "聚焦下一个文件"),
    ("focus previous file", "聚焦上一个文件"),
    ("focus next field", "聚焦下一个字段"),
    ("focus previous field", "聚焦上一个字段"),
    ("open current file", "打开当前文件"),
    ("save skill", "保存技能"),
    ("configure snippets", "配置代码片段"),
    ("show matching keybinds", "显示匹配的按键绑定"),
    ("toggle conflict filter", "切换冲突筛选"),
    ("toggle exact keystroke matching", "切换精确按键匹配"),
    ("toggle keystroke search", "切换按键搜索"),
    ("toggle no action bindings", "切换无操作绑定"),
    ("clear keystrokes", "清除按键"),
    ("start recording", "开始录制"),
    ("stop recording", "停止录制"),
    ("toggle arguments focus", "切换参数聚焦"),
    ("open create keybinding modal", "打开创建按键绑定对话框"),
    ("create binding", "创建绑定"),
    ("delete binding", "删除绑定"),
    ("edit binding", "编辑绑定"),
    ("copy action", "复制操作"),
    ("copy context", "复制上下文"),
    ("open account", "打开账户"),
    ("reset hints", "重置提示"),
    ("run and advance", "运行并前进"),
    ("add code block", "添加代码块"),
    ("add markdown block", "添加 Markdown 块"),
    ("clear outputs", "清除输出"),
    ("delete cell", "删除单元格"),
    ("enter command mode", "进入命令模式"),
    ("enter edit mode", "进入编辑模式"),
    ("interrupt kernel", "中断内核"),
    ("move cell down", "下移单元格"),
    ("move cell up", "上移单元格"),
    ("restart kernel", "重启内核"),
    ("run all", "全部运行"),
    ("open notebook", "打开笔记本"),
    ("toggle changed files view", "切换已更改文件视图"),
    ("toggle tree view", "切换树视图"),
    ("open commit view", "打开提交视图"),
    ("open at commit", "在提交处打开"),
    ("copy commit tag", "复制提交标签"),
    ("toggle semantic tokens", "切换语义标记"),
    ("toggle syntax tokens", "切换语法标记"),
    ("toggle text highlights", "切换文本高亮"),
    ("fit to view", "适应视图"),
    ("use active editor", "使用活动编辑器"),
    ("use selection for find", "使用选区查找"),
    ("focus search", "聚焦搜索"),
    ("focus editor", "聚焦编辑器"),
    ("focus changes", "聚焦更改"),
    ("focus next tab stop", "聚焦下一个制表位"),
    ("focus previous tab stop", "聚焦上一个制表位"),
    ("select all matches", "全选匹配项"),
    ("next history query", "下一个历史记录查询"),
    ("previous history query", "上一个历史记录查询"),
    ("toggle case sensitive", "切换区分大小写"),
    ("toggle include ignored", "切换包含已忽略项"),
    ("toggle selection", "切换选区"),
    ("cycle mode", "循环切换模式"),
    ("open text finder", "打开文本查找"),
    ("toggle all search results", "切换全部搜索结果"),
    ("close selected item", "关闭选中的条目"),
    ("toggle all", "全部切换"),
    ("next project", "下一个项目"),
    ("previous project", "上一个项目"),
    ("next thread", "下一个会话"),
    ("previous thread", "上一个会话"),
    ("close workspace sidebar", "关闭工作区侧边栏"),
    ("focus workspace sidebar", "聚焦工作区侧边栏"),
    ("toggle workspace sidebar", "切换工作区侧边栏"),
    ("toggle workspace sidebar", "切换工作区侧边栏"),
    ("toggle member admin", "切换成员管理员"),
    ("select next control", "选择下一个控件"),
    ("copy link", "复制链接"),
    ("copy room id", "复制房间 ID"),
    ("open channel notes by id", "按 ID 打开频道笔记"),
    ("open channel notes", "打开频道笔记"),
    ("share project", "共享项目"),
    ("show call stats", "显示通话统计"),
    ("simulate update available", "模拟有可用更新"),
    ("switch branch", "切换分支"),
    ("toggle project menu", "切换项目菜单"),
    ("toggle user menu", "切换用户菜单"),
    ("toggle focus nav", "切换导航聚焦"),
    ("toggle focus", "切换聚焦"),
    ("toggle symbols", "切换符号"),
    ("fold directory", "折叠目录"),
    ("unfold directory", "展开目录"),
    ("select next directory", "选择下一个目录"),
    ("select prev directory", "选择上一个目录"),
    ("select next git entry", "选择下一个 Git 条目"),
    ("select prev git entry", "选择上一个 Git 条目"),
    ("select parent", "选择父级"),
    ("select child", "选择子级"),
    ("select first", "选择第一个"),
    ("select last", "选择最后一个"),
    ("select next", "选择下一个"),
    ("select previous", "选择上一个"),
    ("collapse all entries", "折叠全部条目"),
    ("expand all entries", "展开全部条目"),
    ("collapse selected entry", "折叠选中的条目"),
    ("expand selected entry", "展开选中的条目"),
    ("open selected entry", "打开选中的条目"),
    ("reveal in file manager", "在文件管理器中显示"),
    ("reveal in project panel", "在项目面板中显示"),
    ("remove from project", "从项目中移除"),
    ("new search in directory", "在目录中新建搜索"),
    ("new directory", "新建目录"),
    ("open context menu", "打开上下文菜单"),
    ("toggle hide hidden", "切换隐藏隐藏项"),
    ("toggle hide git ignore", "切换隐藏 gitignore 项"),
    ("download from remote", "从远程下载"),
    ("close clean items", "关闭未修改的条目"),
    ("close multibuffer items", "关闭多缓冲区条目"),
    ("close other items", "关闭其他条目"),
    ("close all items", "关闭全部条目"),
    ("activate next item", "激活下一个条目"),
    ("activate previous item", "激活上一个条目"),
    ("activate last item", "激活最后一个条目"),
    ("activate item", "激活条目"),
    ("reopen closed item", "重新打开已关闭的条目"),
    ("close active item", "关闭活动条目"),
    ("alternate file", "切换到备用文件"),
    ("deploy search", "打开搜索"),
    ("go to newer tag", "转到更新的标签"),
    ("go to older tag", "转到更旧的标签"),
    ("toggle preview tab", "切换预览标签页"),
    ("unpin all tabs", "取消固定全部标签页"),
    ("toggle preview", "切换预览"),
    ("set preview below", "将预览设置到下方"),
    ("set preview hidden", "将预览设置为隐藏"),
    ("set preview right", "将预览设置到右侧"),
    ("toggle actions menu", "切换操作菜单"),
    ("confirm input", "确认输入"),
    ("confirm completion", "确认补全"),
    ("toggle data breakpoint", "切换数据断点"),
    ("toggle session picker", "切换会话选择器"),
    ("evaluate selected text", "求值选中的文本"),
    ("go to selected address", "转到选中的地址"),
    ("open project debug tasks", "打开项目调试任务"),
    ("rerun session", "重新运行会话"),
    ("clear all breakpoints", "清除全部断点"),
    ("focus breakpoint list", "聚焦断点列表"),
    ("rate predictions", "评价预测"),
    ("reset onboarding", "重置引导"),
    ("accept edit prediction", "接受编辑预测"),
    ("compose completion", "撰写补全"),
    ("confirm code action", "确认代码操作"),
    ("confirm edit review comment", "确认编辑审查注释"),
    ("cancel edit review comment", "取消编辑审查注释"),
    ("delete review comment", "删除审查注释"),
    ("edit review comment", "编辑审查注释"),
    ("expand excerpts down", "向下展开摘录"),
    ("expand excerpts up", "向上展开摘录"),
    ("expand excerpts", "展开摘录"),
    ("find all references", "查找所有引用"),
    ("go to diagnostic", "转到诊断"),
    ("go to type definition", "转到类型定义"),
    ("handle input", "处理输入"),
    ("insert snippet", "插入代码片段"),
    ("spawn nearest task", "启动最近的任务"),
    ("toggle code actions", "切换代码操作"),
    ("toggle split diff", "切换并排差异视图"),
    ("delete to next subword end", "删除到下一个子词末尾"),
    ("delete to next word end", "删除到下一个单词末尾"),
    ("delete to previous subword start", "删除到上一个子词开头"),
    ("delete to previous word start", "删除到上一个单词开头"),
    ("open debug adapter logs", "打开调试适配器日志"),
    ("open language server logs", "打开语言服务器日志"),
    ("open acp logs", "打开 ACP 日志"),
    ("dump accessibility tree", "转储无障碍树"),
    ("dump input latency histogram", "转储输入延迟直方图"),
    ("dump workspace info", "转储工作区信息"),
    ("debug filesystem watching", "调试文件系统监视"),
    ("copy debug adapter arguments", "复制调试适配器参数"),
    ("edit prediction context go back", "编辑预测上下文后退"),
    ("edit prediction context go forward", "编辑预测上下文前进"),
    ("open edit prediction context view", "打开编辑预测上下文视图"),
    ("open highlights tree view", "打开高亮树视图"),
    ("open key context view", "打开按键上下文视图"),
    ("open syntax tree view", "打开语法树视图"),
    ("open theme preview", "打开主题预览"),
    ("show all sidebar thread metadata", "显示全部侧边栏会话元数据"),
    ("show git job queue", "显示 Git 任务队列"),
    ("show thread metadata", "显示会话元数据"),
    ("show workspace error", "显示工作区错误"),
    ("toggle fps overlay", "切换帧率覆盖层"),
    ("toggle inspector", "切换检查器"),
    ("hang action", "挂起操作"),
    ("hang background", "挂起后台"),
    ("hang foreground", "挂起前台"),
    ("watch expression", "监视表达式"),
    ("run in place", "就地运行"),
    ("refresh kernelspecs", "刷新内核规范"),
    ("clear current output", "清除当前输出"),
    ("start move channel", "开始移动频道"),
    ("move selected", "移动选中的"),
    ("toggle selected channel favorite", "收藏或取消收藏选中的频道"),
    ("toggle selected channel", "切换选中的频道"),
    ("collapse selected channel", "折叠选中的频道"),
    ("expand selected channel", "展开选中的频道"),
    ("insert space", "插入空格"),
    ("remove selected", "移除选中的"),
    ("toggle diagnostic refresh", "切换诊断刷新"),
    ("deploy current file", "打开当前文件"),
    ("open remote", "打开远程"),
    ("open recent", "打开最近项目"),
    ("open folder", "打开文件夹"),
    ("open dev container", "打开开发容器"),
    ("toggle thread history", "切换会话历史记录"),
    ("toggle thread switcher", "切换会话切换器"),
    ("focus sidebar filter", "聚焦侧边栏筛选"),
    ("new thread in group", "在分组中新建会话"),
    ("activate menu left", "激活左侧菜单"),
    ("activate menu right", "激活右侧菜单"),
    ("open application menu", "打开应用菜单"),
    ("inline assist", "行内辅助"),
    ("view release notes", "查看发布说明"),
    ("check for updates", "检查更新"),
    ("dismiss message", "关闭消息"),
    ("show error message", "显示错误消息"),
    ("restart", "重启"),
    ("deafen", "静听"),
    ("reconnect", "重新连接"),
    ("toggle mode", "切换模式"),
    ("toggle direction", "切换方向"),
    ("toggle warnings", "切换警告"),
    ("toggle options menu", "切换选项菜单"),
    ("toggle new thread menu", "切换新建会话菜单"),
    ("toggle command pattern", "切换命令模式"),
    ("toggle fast mode", "切换快速模式"),
    ("toggle thinking mode", "切换思考模式"),
    ("toggle thinking effort menu", "切换思考强度菜单"),
    ("toggle profile selector", "切换配置文件选择器"),
    ("toggle steer first queued message", "切换引导第一条排队消息"),
    ("reset fast mode warnings", "重置快速模式警告"),
    ("reset trial end upsell", "重置试用结束提示"),
    ("reset trial upsell", "重置试用提示"),
    ("manage profiles", "管理配置文件"),
    ("select permission granularity", "选择权限粒度"),
    ("open permission dropdown", "打开权限下拉菜单"),
    ("open add context menu", "打开添加上下文菜单"),
    ("undo last reject", "撤销上一次拒绝"),
    ("edit first queued message", "编辑第一条排队消息"),
    ("remove first queued message", "移除第一条排队消息"),
    ("send next queued message", "发送下一条排队消息"),
    ("clear message queue", "清除消息队列"),
    ("archive selected thread", "归档选中的会话"),
    ("remove selected thread", "移除选中的会话"),
    ("rename selected thread", "重命名选中的会话"),
    ("open active thread as markdown", "将活动会话以 Markdown 打开"),
    ("cycle favorite models", "循环切换收藏的模型"),
    ("cycle thinking effort", "循环切换思考强度"),
    ("cycle next inline assist", "循环切换到下一个行内辅助"),
    ("cycle previous inline assist", "循环切换到上一个行内辅助"),
    ("dismiss thread search", "关闭会话搜索"),
    ("expand message editor", "展开消息编辑器"),
    ("focus down", "向下聚焦"),
    ("focus up", "向上聚焦"),
    ("focus left", "向左聚焦"),
    ("focus right", "向右聚焦"),
    ("open agent diff", "打开智能体差异"),
    ("authorize tool call", "授权工具调用"),
    ("new terminal thread", "新建终端会话"),
    ("new thread", "新建会话"),
    ("thumbs up result", "对结果点赞"),
    ("thumbs down result", "对结果点踩"),
    ("toggle test panel", "切换测试面板"),
    ("some action with docs", "带文档的示例操作"),
    ("some action", "示例操作"),
    ("test action", "测试操作"),
    ("secondary test action", "次要测试操作"),
    ("input action", "输入操作"),
    ("string action", "字符串操作"),
    ("longer binding", "更长的绑定"),
    ("longest binding", "最长的绑定"),
    ("shorter binding", "更短的绑定"),
    ("simulate timeout exhausted", "模拟超时已用尽"),
    ("new journal entry", "新建日志条目"),
    ("toggle check", "切换检查"),
    ("co authors", "共同作者"),
    ("window tab", "窗口标签页"),
    ("system specs", "系统信息"),
    ("open zed url", "打开 Zed 链接"),
    ("helix goto last modification", "Helix 转到上次修改处"),
    ("other end row aware", "另一端（考虑整行）"),
    ("candidate range", "候选范围"),
    ("toggle marks view", "切换标记视图"),
    ("visual insert first non white space", "可视插入到首个非空白字符处"),
    ("candidate", "候选"),
    ("class", "类"),
    ("modification", "修改"),
    ("method", "方法"),
    ("aware", "感知"),
    ("paragraph", "段落"),
    ("sentence", "句子"),
    ("marks", "标记"),
    ("mark", "标记"),
    ("non", "非"),
    ("system", "系统"),
    ("back quotes", "反引号"),
    ("column left", "向左移动一列"),
    ("column right", "向右移动一列"),
    ("insert from above", "从上方插入"),
    ("insert from below", "从下方插入"),
    ("other end", "另一端"),
    ("resize pane down", "向下调整窗格"),
    ("resize pane up", "向上调整窗格"),
    ("resize pane left", "向左调整窗格"),
    ("resize pane right", "向右调整窗格"),
    ("replace with register", "使用寄存器替换"),
    ("to project search", "转到项目搜索"),
    ("change list newer", "更改列表中更新的"),
    ("change list older", "更改列表中更旧的"),
    ("count command", "计数命令"),
    ("normal before", "普通模式之前"),
    ("menu select next", "选择下一个菜单项"),
    ("menu select previous", "选择上一个菜单项"),
    ("window", "窗口"),
    ("percentage", "百分比"),
    ("greater", "更大的"),
    ("lesser", "更小的"),
    ("same", "相同的"),
    ("section", "小节"),
    ("reversed", "反向"),
    ("backward", "向后"),
    ("forward", "向前"),
    ("downward", "向下"),
    ("document", "文档"),
    ("wrapping", "折行"),
    ("open recent project", "打开最近的项目"),
    ("undo last line", "撤销上一行"),
    ("start of paragraph", "段首"),
    ("start of document", "文档开头"),
    ("with count", "带计数"),
    ("with range", "带范围"),
    ("temporary normal", "临时普通模式"),
    ("visual insert end of line", "可视模式在行尾插入"),
    ("next window", "下一个窗口"),
    ("previous window", "上一个窗口"),
    ("move tab to new window", "将标签页移到新窗口"),
    ("next comment", "下一个注释"),
    ("previous comment", "上一个注释"),
    ("next line start", "下一行行首"),
    ("previous line start", "上一行行首"),
    ("next method start", "下一个方法开头"),
    ("next method end", "下一个方法末尾"),
    ("previous method start", "上一个方法开头"),
    ("previous method end", "上一个方法末尾"),
    ("next section start", "下一节开头"),
    ("next section end", "下一节末尾"),
    ("previous section start", "上一节开头"),
    ("previous section end", "上一节末尾"),
    ("next greater indent", "下一个更深缩进"),
    ("next lesser indent", "下一个更浅缩进"),
    ("next same indent", "下一个相同缩进"),
    ("previous greater indent", "上一个更深缩进"),
    ("previous lesser indent", "上一个更浅缩进"),
    ("previous same indent", "上一个相同缩进"),
    ("repeat find reversed", "反向重复查找"),
    ("repeat find", "重复查找"),
    ("go to percentage", "按百分比跳转"),
    ("go to column", "转到列"),
    ("window bottom", "窗口底部"),
    ("window middle", "窗口中间"),
    ("window top", "窗口顶部"),
    ("wrapping left", "向左折行"),
    ("wrapping right", "向右折行"),
    ("toggle project panel focus", "切换项目面板聚焦"),
    ("activate next window", "激活下一个窗口"),
    ("activate previous window", "激活上一个窗口"),
    ("excerpt", "摘录"),
    ("excerpts", "摘录"),
    ("hunk", "差异块"),
    ("hunks", "差异块"),
    ("bookmark", "书签"),
    ("bookmarks", "书签"),
    ("permalink", "永久链接"),
    ("signaturehelp", "签名帮助"),
    ("flycheck", "语法检查"),
    ("recursive", "递归"),
    ("md", "Markdown"),
    ("hover", "悬停"),
    ("revision", "修订"),
    ("base64", "Base64"),
    ("highlight", "高亮"),
    ("highlights", "高亮"),
    ("killring", "剪切环"),
    ("tabstop", "制表位"),
    ("rotate", "轮转"),
    ("insensitive", "不区分"),
    ("numbers", "数字"),
    ("unique", "唯一"),
    ("wrap", "折行"),
    ("tracked", "已跟踪"),
    ("logout", "退出登录"),
    ("global", "全局"),
    ("creator", "创建器"),
    ("raw", "原始"),
    ("reauthenticate", "重新认证"),
    ("copilot", "Copilot"),
    ("predictions", "预测"),
    ("trusted", "受信任"),
    ("security", "安全性"),
    ("centered", "居中"),
    ("banner", "横幅"),
    ("setup", "设置"),
    ("licenses", "许可"),
    ("telemetry", "遥测"),
    ("performance profiler", "性能分析器"),
    ("merch", "周边"),
    ("vs code", "VS Code"),
    ("unfollow", "取消跟随"),
    ("about", "关于"),
    ("read only", "只读"),
    ("suppress", "抑制"),
    ("adapters", "适配器"),
    ("collaborator", "协作者"),
    ("navigation", "导航"),
    ("align", "对齐"),
    ("backtab", "反向制表"),
    ("work", "工作"),
    ("spaces", "空格"),
    ("kebab case", "短横线命名"),
    ("lower camel case", "小驼峰命名"),
    ("upper camel case", "大驼峰命名"),
    ("snake case", "下划线命名"),
    ("title case", "标题式大小写"),
    ("disable", "禁用"),
    ("display", "显示"),
    ("names", "名称"),
    ("macro", "宏"),
    ("ranges", "范围"),
    ("function bodies", "函数体"),
    ("module", "模块"),
    ("uuid", "UUID"),
    ("kill ring", "剪切环"),
    ("reinstall", "重新安装"),
    ("copilot edit predictions", "Copilot 编辑预测"),
    ("fold at", "折叠到"),
    ("convert to", "转换为"),
    ("insert", "插入"),
    ("cancel language server", "取消语言服务器"),
    ("get", "获取"),
    ("enclosing bracket", "外围括号"),
    ("enclosing", "外围的"),
    ("around delimiters", "分隔符周围"),
    ("inside delimiters", "分隔符内部"),
    ("delimiters", "分隔符"),
    ("bracket", "括号"),
    ("brackets", "括号"),
    ("signature help", "签名帮助"),
    ("shuffle", "打乱"),
    ("length", "长度"),
    ("ends", "两端"),
    ("breadcrumb", "面包屑"),
    ("code lens", "代码透镜"),
    ("label", "标签"),
    ("filename", "文件名"),
    ("proposed", "建议的"),
    ("reverse", "反转"),
    ("recursively", "递归地"),
    ("organize imports", "整理导入"),
    ("sort lines by", "按以下方式排序行："),
    ("sort lines", "排序行"),
    ("swap selection ends", "交换选区两端"),
    ("toggle bookmark with label", "切换带标签的书签"),
    ("toggle bookmark", "切换书签"),
    ("switch source header", "在源文件与头文件间切换"),
    ("toggle auto signature help", "切换自动签名帮助"),
    ("signature help next", "下一个签名帮助"),
    ("signature help previous", "上一个签名帮助"),
    ("open selected filename", "打开选中的文件名"),
    ("open proposed changes editor", "打开建议的更改编辑器"),
    ("move to enclosing bracket", "移动到外围括号"),
    ("select enclosing symbol", "选择外围符号"),
    ("select around delimiters", "选择分隔符周围"),
    ("select inside delimiters", "选择分隔符内部"),
    ("expand macro recursively", "递归展开宏"),
    ("indent guides", "缩进参考线"),
    ("guides", "参考线"),
    ("inlay hints", "内联提示"),
    ("inlay", "内联"),
    ("inline values", "行内值"),
    ("minimap", "缩略图"),
    ("relative line numbers", "相对行号"),
    ("line numbers", "行号"),
    ("expanded", "已展开"),
    ("soft wrap", "自动折行"),
    ("tab bar", "标签栏"),
    ("transpose", "转置"),
    ("unwrap", "解包"),
    ("wrap with abbreviation", "用缩写包裹"),
    ("abbreviation", "缩写"),
    ("amend", "修补提交"),
    ("clone", "克隆"),
    ("generate", "生成"),
    ("init", "初始化"),
    ("modified", "已修改"),
    ("signoff", "签名"),
    ("skip hooks", "跳过钩子"),
    ("hooks", "钩子"),
    ("trash", "丢弃"),
    ("untracked", "未跟踪"),
    ("uncommitted", "未提交"),
    ("exclude", "排除"),
    ("return", "返回"),
    ("focused", "聚焦的"),
    ("position", "位置"),
    ("component", "组件"),
    ("worktrees", "工作树"),
    ("project symbols", "项目符号"),
    ("view", "查看"),
    ("close and return to editor", "关闭并返回编辑器"),
    ("add to git info exclude", "添加到 Git 信息排除文件"),
    ("toggle project symbols", "切换项目符号"),
    ("drop current stash", "丢弃当前暂存"),
    ("stash pop", "弹出暂存"),
    ("stash apply", "应用暂存"),
    ("reinstall", "重新安装"),
    ("copilot edit predictions", "Copilot 编辑预测"),
    ("move line down", "向下移动行"),
    ("move line up", "向上移动行"),
    ("duplicate line down", "在下方复制行"),
    ("duplicate line up", "在上方复制行"),
    ("go to declaration split", "转到声明（拆分窗格）"),
    ("go to definition split", "转到定义（拆分窗格）"),
    ("go to implementation split", "转到实现（拆分窗格）"),
    ("go to type definition split", "转到类型定义（拆分窗格）"),
    ("open excerpts split", "打开摘录（拆分窗格）"),
    ("new file split", "新建文件（拆分窗格）"),
    ("confirm", "确认"),
    ("cancel", "取消"),
    ("restart", "重启"),
    ("quit", "退出"),
]

# Namespaces rendered before the colon in an action name.
NAMESPACES = [
    ("activity indicator", "活动指示器"),
    ("agents sidebar", "智能体侧边栏"),
    ("a11y example", "无障碍示例"),
    ("app menu", "应用菜单"),
    ("auto update", "自动更新"),
    ("branch picker", "分支选择器"),
    ("buffer search", "缓冲区搜索"),
    ("call hierarchy", "调用层级"),
    ("channel modal", "频道对话框"),
    ("collab panel", "协作面板"),
    ("command palette", "命令面板"),
    ("component preview", "组件预览"),
    ("context server", "上下文服务器"),
    ("debug panel", "调试面板"),
    ("diagnostics", "诊断"),
    ("dispatch test", "调度测试"),
    ("edit prediction", "编辑预测"),
    ("encoding selector", "编码选择器"),
    ("file finder", "文件查找"),
    ("git graph", "Git 图表"),
    ("git onboarding", "Git 引导"),
    ("git panel", "Git 面板"),
    ("git picker", "Git 选择器"),
    ("hang test", "挂起测试"),
    ("highlights tree view", "高亮树视图"),
    ("icon theme selector", "图标主题选择器"),
    ("image viewer", "图片查看器"),
    ("inline assistant", "行内助手"),
    ("keymap editor", "键映射编辑器"),
    ("keystroke input", "按键输入"),
    ("language selector", "语言选择器"),
    ("line ending selector", "换行符选择器"),
    ("livekit client", "LiveKit 客户端"),
    ("lsp command selector", "LSP 命令选择器"),
    ("lsp tool", "LSP 工具"),
    ("multi workspace", "多工作区"),
    ("new process modal", "新建进程对话框"),
    ("outline panel", "大纲面板"),
    ("pending keystrokes indicator test", "待定按键指示器测试"),
    ("project panel", "项目面板"),
    ("project search", "项目搜索"),
    ("recent projects", "最近的项目"),
    ("remote debug", "远程调试"),
    ("settings editor", "设置编辑器"),
    ("settings profile selector", "设置配置文件选择器"),
    ("skill creator", "技能创建器"),
    ("stash picker", "暂存选择器"),
    ("syntax tree view", "语法树视图"),
    ("tab switcher", "标签页切换器"),
    ("terminal panel", "终端面板"),
    ("test keymap file", "测试键映射文件"),
    ("test only", "仅测试"),
    ("text finder", "文本查找"),
    ("text input", "文本输入框"),
    ("theme selector", "主题选择器"),
    ("variable list", "变量列表"),
    ("view example", "视图示例"),
    ("worktree picker", "工作树选择器"),
    ("set menus", "设置菜单"),
    ("copilot edit predictions", "Copilot 编辑预测"),
    ("go to line", "转到行"),
    ("project symbols", "项目符号"),
    ("tabular data", "表格数据"),
    ("zed predict onboarding", "Zed 预测引导"),
    ("debugger", "调试器"),
    ("assistant", "助手"),
    ("snippets", "代码片段"),
    ("toolchain", "工具链"),
    ("picker", "选择器"),
    ("projects", "项目"),
    ("console", "控制台"),
    ("journal", "日志"),
    ("feedback", "反馈"),
    ("counter", "计数器"),
    ("example", "示例"),
    ("onboarding", "引导"),
    ("agent", "智能体"),
    ("collab", "协作"),
    ("editor", "编辑器"),
    ("workspace", "工作区"),
    ("terminal", "终端"),
    ("search", "搜索"),
    ("outline", "大纲"),
    ("git", "Git"),
    ("zed", "Zed"),
    ("pane", "窗格"),
    ("vim", "Vim"),
    ("helix", "Helix"),
    ("notebook", "笔记本"),
    ("dev", "开发"),
    ("window", "窗口"),
    ("menu", "菜单"),
    ("theme", "主题"),
    ("task", "任务"),
    ("welcome", "欢迎"),
    ("toast", "提示条"),
    ("image", "图片"),
    ("client", "客户端"),
    ("markdown", "Markdown"),
    ("zeta", "Zeta"),
    ("repl", "REPL"),
    ("cli", "命令行"),
    ("svg", "SVG"),
    ("bedrock", "Bedrock"),
]

# Names that the composer gets wrong, or that read better as a whole.
OVERRIDES = {
    # `push` is a git operation here, but starts a vim operator there.
    "git: push": "Git：推送",
    "git: force push": "Git：强制推送",
    "git: push to": "Git：推送到",
    # The workspace and zed namespaces are the ones users see most often in the
    # command palette, so they are written out by hand.
    "workspace: activate pane down": "工作区：激活下方窗格",
    "workspace: activate pane left": "工作区：激活左侧窗格",
    "workspace: activate pane right": "工作区：激活右侧窗格",
    "workspace: activate pane up": "工作区：激活上方窗格",
    "workspace: add folder to project": "工作区：将文件夹添加到项目",
    "workspace: clear navigation history": "工作区：清除导航历史记录",
    "workspace: clear trusted worktrees": "工作区：清除受信任的工作树",
    "workspace: close all docks": "工作区：关闭所有停靠栏",
    "workspace: close item in all panes": "工作区：在所有窗格中关闭该条目",
    "workspace: follow next collaborator": "工作区：跟随下一个协作者",
    "workspace: move focused panel to next position": "工作区：将聚焦的面板移到下一个位置",
    "workspace: move item to pane": "工作区：将条目移到窗格",
    "workspace: move item to pane in direction": "工作区：按方向将条目移到窗格",
    "workspace: move pane down": "工作区：向下移动窗格",
    "workspace: move pane left": "工作区：向左移动窗格",
    "workspace: move pane right": "工作区：向右移动窗格",
    "workspace: move pane up": "工作区：向上移动窗格",
    "workspace: open component preview": "工作区：打开组件预览",
    "workspace: open in terminal": "工作区：在终端中打开",
    "workspace: open with system": "工作区：用系统默认应用打开",
    "workspace: restore banner": "工作区：恢复横幅",
    "workspace: save without format": "工作区：保存但不格式化",
    "workspace: shutdown debug adapters": "工作区：关闭调试适配器",
    "workspace: suppress notification": "工作区：抑制通知",
    "workspace: swap pane adjacent": "工作区：与相邻窗格交换",
    "workspace: swap pane down": "工作区：与下方窗格交换",
    "workspace: swap pane left": "工作区：与左侧窗格交换",
    "workspace: swap pane right": "工作区：与右侧窗格交换",
    "workspace: swap pane up": "工作区：与上方窗格交换",
    "workspace: toggle all docks": "工作区：切换所有停靠栏",
    "workspace: toggle centered layout": "工作区：切换居中布局",
    "workspace: toggle read only file": "工作区：切换只读",
    "workspace: toggle worktree security": "工作区：切换工作树安全设置",
    "workspace: unfollow": "工作区：取消跟随",
    "zed: about": "Zed：关于",
    "zed: get merch": "Zed：获取周边",
    "zed: import vs code settings": "Zed：导入 VS Code 设置",
    "zed: open licenses": "Zed：打开许可信息",
    "zed: open performance profiler": "Zed：打开性能分析器",
    "zed: open settings at": "Zed：在指定位置打开设置",
    "zed: open telemetry log": "Zed：打开遥测日志",
    "zed: open worktree setup tasks": "Zed：打开工作树设置任务",
    "zed: reveal log in file manager": "Zed：在文件管理器中显示日志",
    "zed: test panic": "Zed：测试 panic",
    "zed: toggle full screen": "Zed：切换全屏",
    "zeta: thumbs down active prediction": "Zeta：对当前预测点踩",
    "zeta: thumbs up active prediction": "Zeta：对当前预测点赞",
}

MAX_PHRASE_WORDS = 6

# `fold at level3` and friends: the humanizer turns `FoldAtLevel3` into a single
# token that carries its number.
LEVEL = re.compile(r"level(\d+)$")

ACTIONS_MACRO = re.compile(r"actions!\(")
ACTION_NAME = re.compile(r"^\s*([A-Z][A-Za-z0-9_]*)\s*,?\s*$", re.M)
ACTION_ATTR = re.compile(r"#\[action\(([^)]*)\)\]")
NAMESPACE_ATTR = re.compile(r"namespace\s*=\s*([a-zA-Z_][a-zA-Z_0-9]*)")
STRUCT = re.compile(r"^\s*pub struct ([A-Za-z0-9_]+)", re.M)
DERIVE = re.compile(r"#\[derive\(([^)]*)\)\]", re.S)


def humanize(name: str) -> str:
    """Port of `command_palette::humanize_action_name`."""
    chars = list(name)
    result = []
    index = 0
    while index < len(chars):
        char = chars[index]
        if char == ":":
            if result and result[-1] == ":":
                result.append(" ")
            else:
                result.append(":")
            index += 1
        elif char == "_":
            result.append(" ")
            index += 1
        elif char.isupper():
            start = index
            index += 1
            while index < len(chars) and chars[index].isupper():
                index += 1
            run = chars[start:index]
            if len(run) > 1:
                split_before_last = index < len(chars) and chars[index].islower()
                acronym_end = len(run) - 1 if split_before_last else len(run)
                if acronym_end > 0:
                    if result and result[-1] != " ":
                        result.append(" ")
                    result.extend(run[:acronym_end])
                if split_before_last:
                    if result and result[-1] != " ":
                        result.append(" ")
                    result.extend(run[acronym_end].lower())
            else:
                if result and result[-1] != " ":
                    result.append(" ")
                result.extend(char.lower())
        else:
            result.append(char)
            index += 1
    return "".join(result)


def action_macros(source: str):
    """Yields (namespace, body) for every `actions!` invocation.

    The body is scanned bracket by bracket rather than matched with a regular
    expression, because it contains attributes with brackets of their own.
    """
    for match in ACTIONS_MACRO.finditer(source):
        arguments = match.end()
        open_index = source.find("[", arguments)
        if open_index < 0:
            continue
        depth = 0
        for position in range(open_index, len(source)):
            character = source[position]
            if character == "[":
                depth += 1
            elif character == "]":
                depth -= 1
                if depth == 0:
                    namespace = source[arguments:open_index].strip().rstrip(",").strip()
                    yield namespace or None, source[open_index + 1 : position]
                    break


def collect_actions(root: str):
    """Returns every humanized action name in the source tree."""
    names = set()
    for dirpath, dirnames, filenames in os.walk(os.path.join(root, "crates")):
        dirnames[:] = [name for name in dirnames if name != "target"]
        for filename in filenames:
            if not filename.endswith(".rs"):
                continue
            path = os.path.join(dirpath, filename)
            with open(path, encoding="utf-8", errors="replace") as handle:
                source = handle.read()

            for namespace, body in action_macros(source):
                for name in ACTION_NAME.findall(body):
                    names.add(full_name(namespace, name))

            for match in ACTION_ATTR.finditer(source):
                namespace = NAMESPACE_ATTR.search(match.group(1))
                struct = STRUCT.search(source, match.end(), match.end() + 2000)
                if namespace and struct:
                    names.add(full_name(namespace.group(1), struct.group(1)))

            for match in DERIVE.finditer(source):
                if "Action" not in match.group(1):
                    continue
                struct = STRUCT.search(source, match.end(), match.end() + 2000)
                if not struct:
                    continue
                if ACTION_ATTR.search(source, match.end(), match.end() + 2000):
                    continue
                names.add(full_name(None, struct.group(1)))

    return {humanize(name) for name in names}


def full_name(namespace, name):
    return f"{namespace}::{name}" if namespace else name


def compose(body: str, phrases) -> str:
    tokens = body.split()
    parts = []
    index = 0
    while index < len(tokens):
        numbered = LEVEL.match(tokens[index])
        if numbered:
            parts.append(f"第 {numbered.group(1)} 层")
            index += 1
            continue
        translation = None
        for length in range(min(MAX_PHRASE_WORDS, len(tokens) - index), 0, -1):
            phrase = tuple(tokens[index : index + length])
            if phrase in phrases:
                translation = (length, phrases[phrase])
                break
        if translation is None:
            parts.append(tokens[index])
            index += 1
        else:
            length, text = translation
            parts.append(text)
            index += length
    return join(parts)


def join(parts) -> str:
    """Joins translations, keeping a space between a Chinese and a Latin word."""
    result = ""
    for part in parts:
        if not part:
            continue
        if result and needs_space(result[-1], part[0]):
            result += " "
        result += part
    return result


def needs_space(previous: str, following: str) -> bool:
    if is_ascii_word(previous) and is_ascii_word(following):
        return True
    return (is_ascii_word(previous) and is_chinese(following)) or (
        is_chinese(previous) and is_ascii_word(following)
    )


def is_chinese(char: str) -> bool:
    return "\u3400" <= char <= "\u9fff" or "\uf900" <= char <= "\ufaff"


def is_ascii_word(char: str) -> bool:
    return char.isascii() and char.isalnum()


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)

    root = sys.argv[1]
    output = sys.argv[2]
    if not os.path.isdir(root):
        root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    phrases = {}
    for phrase, translation in PHRASES:
        phrases.setdefault(tuple(phrase.split()), translation)
    namespaces = dict(NAMESPACES)

    translated = {}
    for name in sorted(collect_actions(root)):
        if name in OVERRIDES:
            translated[name] = OVERRIDES[name]
            continue
        if ": " in name:
            namespace, body = name.split(": ", 1)
        else:
            namespace, body = None, name
        text = compose(body, phrases)
        if namespace:
            prefix = namespaces.get(namespace, namespace)
            text = f"{prefix}：{text}" if text else prefix
        if text and text != name:
            translated[name] = text

    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(translated, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"{len(translated)} action names translated into {output}")


if __name__ == "__main__":
    main()
